spring:
    profiles:
        active: local
    application:
        name: matchingplatform

logging:
    level:
        root: info
    pattern:
        console: "%blue(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%highlight(%-5level)] %yellow(%thread) %cyan(%logger{36}) %magenta([traceId=%X{traceId}]) - %msg%n"

server:
    port: 8080

toss:
    secret-key: "test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm"